services:
  backend:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env.local

  postgres:
    image: postgres
    env_file:
      - .env.local
    ports:
      - 5432:5432

  redis_db:
    image: redis
    ports:
      - 6379:6379
    env_file:
      - .env.local
